name: Pipeline CI - TCD Flavio

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Permite execução MANUAL
  schedule:
    - cron: '0 3 * * *' # Execução AGENDADA (todo dia às 3h da manhã)

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Instalar Dependências
        run: npm install

      # Roda os testes e gera o relatório no formato padronizado xUnit (XML)
      - name: Rodar Testes com Relatório
        run: npx mocha test/*.test.js --reporter xunit > report.xml
        continue-on-error: true # Garante que a pipeline continue para salvar o relatório mesmo se um teste falhar

      # ARMAZENAMENTO/PUBLICAÇÃO do relatório na pipeline (Requisito do TCD)
      - name: Publicar Relatório de Testes
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-de-testes
          path: report.xml